services:
  openresty:
    image: docker.sabz.dev/openresty/openresty:alpine
    container_name: openresty
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
    depends_on:
      - redis

  redis:
    image: docker.sabz.dev/redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
